image: maven:3-jdk-8
before_script:
 -
  source ./env-variable.sh
stages:
 -
  test
 -
  build
services:
 - 
  'mysql:latest'
variables:
 MYSQL_DATABASE: foodiedb
 MYSQL_CI_URL: jdbc:mysql://mysql/foodiedb
 MYSQL_USER: root
 MYSQL_ROOT_PASSWORD: root
cache:
 paths:
  - .m2/repository/
  - target
maven-test:
 stage: test
 script: "mvn test -B"
maven-build:
 stage: build
 script: "mvn package -U"  
 artifacts:
  paths:
   - target/*.jar